name: "Setup"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2.4.0
      with:
        version:

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'

    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "znro001@126.com"
        git config --global user.name "Vc-great"

    - name: Install dependencies
      shell: bash
      run: pnpm install --prefer-offline

    - name: Setup Turbo
      uses: dtinth/setup-github-actions-caching-for-turbo@v1.2.0
      continue-on-error: true
      with:
        # Set the prefix for the cache keys.
        cache-prefix: openapiTo_
