name: e2e

on:
  push:
    branches: [V2]
jobs:
  common:
      name: Build and test
      timeout-minutes: 30
      strategy:
        fail-fast: true
        matrix:
          os: [ubuntu-latest, windows-latest,macos-latest]
          node-version: [18]
          installer: ['pnpm run']
      runs-on: ${{ matrix.os }}
      continue-on-error: ${{ matrix.experimental || false }}

      steps:
        - name: Check out code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2

        - name: Setup
          uses: ./.github/setup

        - name: Build
          run: ${{ matrix.installer }} build

        - name: Install e2e dependencies
          run: pnpm install --prefer-offline
          working-directory: ./e2e/common

        - name: E2e  openapi-to init
          working-directory: ./e2e/common
          run:  ${{ matrix.installer }} init

        - name: E2e  openapi-to edit plugins
          working-directory: ./e2e/common
          run: ${{ matrix.installer }} editPlugins

        - name: openapi-to generate
          working-directory: ./e2e/common
          env:
            NODE_OPTIONS: "--max_old_space_size=4096"
          run:  ${{ matrix.installer }} generate

  moudle:
    name: Build and test
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest,macos-latest ]
        node-version: [ 18 ]
        installer: [ 'pnpm run' ]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup
        uses: ./.github/setup

      - name: Build
        run: ${{ matrix.installer }} build

      - name: Install e2e dependencies
        run: pnpm install --prefer-offline
        working-directory: ./e2e/module

      - name: E2e  openapi-to init
        working-directory: ./e2e/module
        run: ${{ matrix.installer }} init

      - name: E2e  openapi-to edit plugins
        working-directory: ./e2e/module
        run: ${{ matrix.installer }} editPlugins

      - name: openapi-to generate
        working-directory: ./e2e/module
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: ${{ matrix.installer }} generate

